# to add WA metadata into the build without overlay, you can create a custom
# snakemake rule like so below on lines 3 and 4
#custom_rules:
 # - wa_mpxv/add_wa_metadata.smk


reference: "defaults/reference.fasta"
ancestral_root_seq: "defaults/reference.fasta"
genome_annotation: "defaults/genome_annotation.gff3"
genbank_reference: "defaults/reference.gb"
include: "defaults/hmpxv1/include.txt"
clades: "defaults/clades.tsv"
lat_longs: "defaults/lat_longs.tsv"
auspice_config: "wa_mpxv/wa_auspice_config_hmpxv1.json"
description: "wa_mpxv/wa_description.md"
tree_mask: "defaults/tree_mask.tsv"

strain_id_field: "accession"
display_strain_field: "strain"


build_name: "hmpxv1_wa"
auspice_name: "mpox_wa"

filter:
  min_date: 2017
  min_length: 100000


subsample:
  wa:
    group_by: "--group-by division year"
    sequences_per_group: "--sequences-per-group 500"
    other_filters: "--exclude-where division!=Washington"
    force: true
  global:
    group_by: "--group-by lineage"
    sequences_per_group: "--subsample-max-sequences 500"
    other_filters: "--exclude-where division=Washington outbreak!=hMPXV-1 clade!=IIb"


## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: true
treefix_root: "--root MK783032"

## refine
timetree: true
root: "MK783032 MK783030"
clock_rate: 5.7e-5
clock_std_dev: 2e-5
divergence_units: "mutations"

traits:
  columns: ""
  sampling_bias_correction: 3

## recency
recency: true

mask:
  from_beginning: 800
  from_end: 6422
  maskfile: "defaults/mask.bed"
